export const ENEMY_TYPES = {
  NORMAL: {
    type: 'RANGED',
    texture: 'soldier-walking',
    hp: 100,
    speed: 120,
    visionRange: 350,
    attackRange: 120,
    retreatRange: 90,
    fireRate: 800,
    damage: 10,
    scale: 0.1,
    colorTint: 0x75b36b,
    healReward: 15,
  },
  SNIPER: {
    type: 'RANGED',
    texture: 'soldier-walking',
    hp: 50,
    speed: 150,
    visionRange: 600,
    attackRange: 450,
    retreatRange: 250,
    fireRate: 3000,
    damage: 40,
    scale: 0.08,
    colorTint: 0xd9eda4, // Verde
    healReward: 30,
  },
  TANK: {
    type: 'RANGED',
    texture: 'soldier-walking',
    hp: 350,
    speed: 60,
    visionRange: 250,
    attackRange: 100,
    retreatRange: 0,
    fireRate: 1500,
    damage: 20,
    scale: 0.15, // Más grande
    colorTint: 0xff0000, // Rojo
    healReward: 50,
  },
  MILITAR: {
    type: 'RANGED',
    texture: 'soldier-walking',
    hp: 180,
    speed: 150,
    visionRange: 400,
    attackRange: 220,
    retreatRange: 100,
    fireRate: 500,
    damage: 15,
    scale: 0.11,
    colorTint: 0x1b5c1b,
    healReward: 25,
  },
  KAMIKAZE: {
    type: 'KAMIKAZE',
    texture: 'soldier-walking',
    hp: 60,
    speed: 190,
    visionRange: 500,
    attackRange: 40,
    retreatRange: 0, // No huye
    fireRate: 0,
    damage: 80,
    scale: 0.09,
    colorTint: 0xffc347,
    healReward: 20,
  },
  MELEE: {
    type: 'MELEE',
    texture: 'soldier-walking',
    hp: 130,
    speed: 150,
    visionRange: 350,
    attackRange: 50,
    retreatRange: 0, // No huye
    fireRate: 1000,
    damage: 25,
    scale: 0.1,
    colorTint: 0xcc00ff,
    healReward: 20,
  },
  MEDIC: {
    type: 'MEDIC',
    texture: 'soldier-walking',
    hp: 90,
    speed: 140,
    visionRange: 400,
    attackRange: 60,
    retreatRange: 0,
    fireRate: 1000,
    damage: -25,
    scale: 0.095,
    colorTint: 0x00ffff,
    healReward: 20,
  },
};
